# Form implementation generated from reading ui file 'ui/MainPage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1330, 824)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAddDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddDialog.setGeometry(QtCore.QRect(390, 220, 93, 28))
        self.btnAddDialog.setObjectName("btnAddDialog")
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(110, 220, 93, 28))
        self.btnDelete.setObjectName("btnDelete")
        self.btnEditDialog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEditDialog.setGeometry(QtCore.QRect(250, 220, 93, 28))
        self.btnEditDialog.setObjectName("btnEditDialog")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1301, 91))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui\\../image/steam logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.test = QtWidgets.QListWidget(parent=self.centralwidget)
        self.test.setGeometry(QtCore.QRect(140, 280, 341, 311))
        self.test.setObjectName("test")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(140, 130, 51, 41))
        self.btnSearch.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.btnSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../../../../Downloads/Sản phẩm cuối kì/Images/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSearch.setIcon(icon)
        self.btnSearch.setObjectName("btnSearch")
        self.txtValueSearch = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtValueSearch.setGeometry(QtCore.QRect(260, 130, 631, 53))
        self.txtValueSearch.setMinimumSize(QtCore.QSize(0, 53))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.txtValueSearch.setFont(font)
        self.txtValueSearch.setText("")
        self.txtValueSearch.setObjectName("txtValueSearch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1330, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddDialog.setText(_translate("MainWindow", "Add"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.btnEditDialog.setText(_translate("MainWindow", "Edit"))
        self.txtValueSearch.setPlaceholderText(_translate("MainWindow", "Search your games here !?!"))
